# Generated by Django 3.0 on 2019-12-31 21:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191231_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_overview',
            field=models.TextField(default=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
