# Generated by Django 3.0 on 2020-01-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_overview',
            field=models.CharField(max_length=200),
        ),
    ]
