# Generated by Django 3.0.1 on 2020-01-08 14:27

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_category_programmingposts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=froala_editor.fields.FroalaField(),
        ),
        migrations.AlterField(
            model_name='programmingposts',
            name='content',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
