# Generated by Django 3.0.1 on 2020-01-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200108_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categorise',
            field=models.ManyToManyField(to='blog.Category'),
        ),
    ]
