# Generated by Django 3.0.1 on 2020-01-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_post_categorise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categorise',
            field=models.ManyToManyField(default='Programming', to='blog.Category'),
        ),
    ]
