# Generated by Django 3.0.1 on 2020-01-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20200108_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.CharField(default='Programming', max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='categorise',
            field=models.ManyToManyField(to='blog.Category'),
        ),
    ]
