# Generated by Django 3.0.1 on 2020-01-09 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_post_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('singnup_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='programmingposts',
            name='author',
        ),
        migrations.RemoveField(
            model_name='programmingposts',
            name='categorise',
        ),
        migrations.RemoveField(
            model_name='post',
            name='categorise',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='ProgrammingPosts',
        ),
    ]
